apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  labels:
    purpose: ingress-demo
    project: roboshop
    app: app2
spec:
  replicas: 2
  selector: 
    matchLabels:
      purpose: ingress-demo
      project: roboshop
      app: app2
  template:
    metadata:
      labels:
        purpose: ingress-demo
        project: roboshop
        app: app2
    spec:
      containers:
      - name: app2
        image: bsainitin/app2:v1
---
apiVersion: v1 
kind: Service
metadata:
  name: app2
spec:
  selector:
    purpose: ingress-demo
    project: roboshop
    app: app2
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app2
  annotations:
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS": 443}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:558232169669:certificate/7bd03da3-3d23-49db-bedb-33da573dc3bd
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/tags: Environment=dev,Project=roboshop
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/group.name: roboshop
spec:
  ingressClassName: alb
  rules:
  - host: "app2.theawsdevops.space"
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: app2
            port:
              number: 80 